[package]
name = "bo-tie-host-util"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.0", optional = true }

[features]
"uuid-crate" = ["uuid"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]