[package]
name = "bo-tie-l2cap"
version = "0.1.0"
edition = "2021"

[dependencies]
bo-tie-core = { path = "../../bo-tie-core" }

[features]
std = []
unstable = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
