[package]
name = "connect-master"
version = "0.1.0"
edition = "2021"

[dependencies]
bo-tie = { path = "../../bo-tie" }
bo-tie-linux = { path = "../../base-crates/bo-tie-linux"}
futures = "0.3"
simplelog = "0.11"
simple-signal = "1"
getopts = "0.2"